import { countProducts, upsertProduct, UpsertProductInput } from './services/productService';

const sampleCatalog: UpsertProductInput[] = [
    {
        id: 'REF001',
        slug: 'radio-android-9-mazda-3',
        name: 'Radio Android 9" Mazda 3',
        category: 'Radios Android',
        brand: 'JNB Android',
        compatibility: 'Mazda 3 2014 - 2018',
        description: 'Pantalla táctil Full HD de 9 pulgadas con GPS integrado, Bluetooth 5.0 y WiFi. Incluye marco de instalación específico para Mazda 3 e instalación profesional.',
        price: 1250000,
        stock: 12,
        status: 'Activo',
        images: ['radio-android-9-mazda-3.svg'],
    },
    {
        id: 'REF002',
        slug: 'tapetes-termoformados-a-medida',
        name: 'Tapetes Termoformados a Medida',
        category: 'Interior',
        brand: 'JNB Interior',
        compatibility: 'Universal (a medida por modelo)',
        description: 'Tapetes termoformados de alta precisión, resistentes al agua y al desgaste. Ajuste exacto para el piso de tu vehículo.',
        price: 249000,
        stock: 30,
        status: 'Activo',
        images: ['tapetes-termoformados-a-medida.svg'],
    },
    {
        id: 'REF003',
        slug: 'caja-turbo-subwoofer',
        name: 'Caja Turbo Subwoofer Bajos Precisos',
        category: 'Car Audio',
        brand: 'JNB Audio',
        compatibility: 'Universal',
        description: 'Subwoofer en caja turbo de diseño compacto, graves profundos y precisos para todo tipo de vehículo.',
        price: 450000,
        stock: 18,
        status: 'Activo',
        images: ['caja-turbo-subwoofer.svg'],
    },
    {
        id: 'REF004',
        slug: 'bombillos-led-k1-pro',
        name: 'Bombillos LED JNB-IHK K1 PRO',
        category: 'Iluminación LED',
        brand: 'JNB-IHK',
        compatibility: 'Universal (H1, H4, H7, H11, 9005, 9006)',
        description: 'Tecnología LED de última generación, 3 veces más luminosidad que el halógeno tradicional. Instalación plug & play.',
        price: 180000,
        stock: 40,
        status: 'Activo',
        images: ['bombillos-led-k1-pro.svg'],
    },
    {
        id: 'REF005',
        slug: 'camara-reversa-hd',
        name: 'Cámara de Reversa HD',
        category: 'Cámaras',
        brand: 'JNB Vision',
        compatibility: 'Universal',
        description: 'Cámara de reversa de alta definición con visión nocturna y líneas de guía dinámicas para un parqueo seguro.',
        price: 120000,
        stock: 25,
        status: 'Activo',
        images: ['camara-reversa-hd.svg'],
    },
    {
        id: 'REF006',
        slug: 'amplificador-4-canales-1000w',
        name: 'Amplificador 4 Canales 1000W',
        category: 'Car Audio',
        brand: 'JNB Audio',
        compatibility: 'Universal',
        description: 'Amplificador de 4 canales con potencia máxima de 1000W, protección térmica y contra cortocircuitos.',
        price: 380000,
        stock: 15,
        status: 'Activo',
        images: ['amplificador-4-canales-1000w.svg'],
    },
    {
        id: 'REF007',
        slug: 'radio-universal-7-android-12',
        name: 'Radio Universal 7" Android 12',
        category: 'Radios Android',
        brand: 'JNB Android',
        compatibility: 'Universal (2 DIN)',
        description: 'Radio Android 12 universal de 7 pulgadas con GPS, Bluetooth, WiFi y compatibilidad con Carplay/Android Auto.',
        price: 890000,
        stock: 10,
        status: 'Activo',
        images: ['radio-universal-7-android-12.svg'],
    },
    {
        id: 'REF008',
        slug: 'alarma-sensor-presencia',
        name: 'Alarma con Sensor de Presencia',
        category: 'Alarmas',
        brand: 'JNB Security',
        compatibility: 'Universal',
        description: 'Sistema de alarma vehicular con sensor de presencia, control remoto de doble vía y cierre centralizado.',
        price: 220000,
        stock: 20,
        status: 'Activo',
        images: ['alarma-sensor-presencia.svg'],
    },
];

export const seedSampleCatalogIfEmpty = (): void => {
    if (countProducts() > 0) return;
    for (const product of sampleCatalog) upsertProduct(product);
    console.warn(`⚠️  Catálogo vacío: se cargaron ${sampleCatalog.length} productos de MUESTRA. Reemplázalos importando tu inventario real (ver "npm run import:excel").`);
};
