import { countProducts, upsertProduct, UpsertProductInput } from './services/productService';

export const sampleCatalog: UpsertProductInput[] = [
    {
        id: 'REF101',
        slug: 'tweeter-jnb-3',
        name: 'Tweeter JNB PRO',
        category: 'Car Audio',
        brand: 'JNB Audio',
        compatibility: 'Universal (2 y 3 vías)',
        description: 'Tweeter JNB de alta definición con cúpula reforzada para agudos cristalinos y sin distorsión. Cuerpo en aluminio mecanizado con acabado premium.',
        price: 95000,
        stock: 40,
        status: 'Activo',
        images: ['tweeter-jnb-3.png'],
    },
    {
        id: 'REF102',
        slug: 'tweeter-jnb-caja-sonido',
        name: 'Tweeter JNB para Caja de Sonido',
        category: 'Car Audio',
        brand: 'JNB Audio',
        compatibility: 'Universal',
        description: 'Tweeter JNB de montaje angular, pensado para instalación en caja de sonido personalizada. Respuesta de agudos precisa y potente.',
        price: 98000,
        stock: 35,
        status: 'Activo',
        images: ['tweeter-jnb-caja-sonido.png'],
    },
    {
        id: 'REF103',
        slug: 'radio-toyota-4runner-2017',
        name: 'Radio Android Toyota 4Runner (4GB/64GB)',
        category: 'Radios Android',
        brand: 'JNB Android',
        compatibility: 'Toyota 4Runner 2017 - 2020',
        description: 'Pantalla vertical estilo Tesla con Android integrado, 4GB de RAM y 64GB de almacenamiento. Apple CarPlay y Android Auto inalámbricos, GPS y control climático integrado en pantalla.',
        price: 2350000,
        stock: 6,
        status: 'Activo',
        images: ['radio-toyota-4runner-2017.webp'],
    },
    {
        id: 'REF104',
        slug: 'tercer-stop-led-fortuner',
        name: 'Tercer Stop LED OEM Toyota Fortuner',
        category: 'Iluminación LED',
        brand: 'JNB-IHK',
        compatibility: 'Toyota Fortuner 2016 - 2020',
        description: 'Luz de freno adicional (tercer stop) LED estilo OEM, barra continua con encendido secuencial. Instalación plug & play, sin modificar el cableado original.',
        price: 210000,
        stock: 15,
        status: 'Activo',
        images: ['tercer-stop-led-fortuner.webp'],
    },
    {
        id: 'REF105',
        slug: 'timon-corolla-cross-gr',
        name: 'Timón Corolla Cross GR Original',
        category: 'Interior',
        brand: 'Toyota GR',
        compatibility: 'Toyota Corolla Cross GR',
        description: 'Volante original línea GR para Corolla Cross, cuero perforado con costura roja, paletas de cambio y controles multifunción integrados.',
        price: 1450000,
        stock: 4,
        status: 'Activo',
        images: ['timon-corolla-cross-gr.png'],
    },
    {
        id: 'REF106',
        slug: 'timon-lexus-carbono',
        name: 'Timón Lexus Fibra de Carbono',
        category: 'Interior',
        brand: 'Lexus',
        compatibility: 'Lexus (línea F Sport)',
        description: 'Volante deportivo con inserciones en fibra de carbono real, cuero premium y controles multifunción. Acabado línea F.',
        price: 1780000,
        stock: 3,
        status: 'Activo',
        images: ['timon-lexus-carbono.png'],
    },
    {
        id: 'REF107',
        slug: 'timon-palo-rosa-toyota',
        name: 'Timón Palo Rosa Toyota',
        category: 'Interior',
        brand: 'Toyota',
        compatibility: 'Toyota (línea Palo Rosa)',
        description: 'Volante con acabado en palo rosa y cuero negro, controles multifunción integrados. Elegancia clásica para el interior de tu vehículo.',
        price: 1120000,
        stock: 5,
        status: 'Activo',
        images: ['timon-palo-rosa-toyota.png'],
    },
];

export const seedSampleCatalogIfEmpty = (): void => {
    if (countProducts() > 0) return;
    for (const product of sampleCatalog) upsertProduct(product);
    console.warn(`⚠️  Catálogo vacío: se cargaron ${sampleCatalog.length} productos reales de arranque. Los precios y el stock son valores iniciales — actualízalos importando tu inventario real (ver "npm run import:excel").`);
};
