import { countProducts, upsertProduct, UpsertProductInput } from './services/productService';

export const sampleCatalog: UpsertProductInput[] = [
    {
        id: 'REF101',
        slug: 'tweeter-jnb-3',
        name: 'Tweeter JNB PRO',
        category: 'Car Audio',
        brand: 'JNB Audio',
        compatibility: 'Universal (2 y 3 vías)',
        description: 'Tweeter JNB de alta definición con cúpula reforzada para agudos cristalinos y sin distorsión. Cuerpo en aluminio mecanizado con acabado premium.',
        price: 95000,
        stock: 40,
        status: 'Activo',
        images: ['tweeter-jnb-3.png'],
        vehicleBrand: 'Universal',
        vehicleModel: '',
    },
    {
        id: 'REF102',
        slug: 'tweeter-jnb-caja-sonido',
        name: 'Tweeter JNB para Caja de Sonido',
        category: 'Car Audio',
        brand: 'JNB Audio',
        compatibility: 'Universal',
        description: 'Tweeter JNB de montaje angular, pensado para instalación en caja de sonido personalizada. Respuesta de agudos precisa y potente.',
        price: 98000,
        stock: 35,
        status: 'Activo',
        images: ['tweeter-jnb-caja-sonido.png'],
        vehicleBrand: 'Universal',
        vehicleModel: '',
    },
    {
        id: 'REF104',
        slug: 'tercer-stop-led-fortuner',
        name: 'Tercer Stop LED OEM Toyota Fortuner',
        category: 'Iluminación LED',
        brand: 'JNB-IHK',
        compatibility: 'Toyota Fortuner 2016 - 2020',
        description: 'Luz de freno adicional (tercer stop) LED estilo OEM, barra continua con encendido secuencial. Instalación plug & play, sin modificar el cableado original.',
        price: 210000,
        stock: 15,
        status: 'Activo',
        images: ['tercer-stop-led-fortuner-studio.png'],
        vehicleBrand: 'Toyota',
        vehicleModel: 'Fortuner',
    },
    {
        id: 'REF105',
        slug: 'timon-corolla-cross-gr',
        name: 'Timón Corolla Cross GR Original',
        category: 'Interior',
        brand: 'Toyota GR',
        compatibility: 'Toyota Corolla Cross GR',
        description: 'Volante original línea GR para Corolla Cross, cuero perforado con costura roja, paletas de cambio y controles multifunción integrados.',
        price: 1450000,
        stock: 4,
        status: 'Activo',
        images: ['timon-corolla-cross-gr.png'],
        vehicleBrand: 'Toyota',
        vehicleModel: 'Corolla Cross',
    },
    {
        id: 'REF106',
        slug: 'timon-lexus-carbono',
        name: 'Timón Lexus Fibra de Carbono',
        category: 'Interior',
        brand: 'Lexus',
        compatibility: 'Lexus (línea F Sport)',
        description: 'Volante deportivo con inserciones en fibra de carbono real, cuero premium y controles multifunción. Acabado línea F.',
        price: 1780000,
        stock: 3,
        status: 'Activo',
        images: ['timon-lexus-carbono.png'],
        vehicleBrand: 'Lexus',
        vehicleModel: 'Varios modelos (F Sport)',
    },
    {
        id: 'REF107',
        slug: 'timon-palo-rosa-toyota',
        name: 'Timón Palo Rosa Toyota',
        category: 'Interior',
        brand: 'Toyota',
        compatibility: 'Toyota (línea Palo Rosa)',
        description: 'Volante con acabado en palo rosa y cuero negro, controles multifunción integrados. Elegancia clásica para el interior de tu vehículo.',
        price: 1120000,
        stock: 5,
        status: 'Activo',
        images: ['timon-palo-rosa-toyota.png'],
        vehicleBrand: 'Toyota',
        vehicleModel: 'Varios modelos',
    },
    {
        id: 'REF108',
        slug: 'camara-reversa-hd',
        name: 'Cámara de Reversa HD Visión Nocturna',
        category: 'Cámaras y Seguridad',
        brand: 'JNB Security',
        compatibility: 'Universal — cualquier radio o pantalla con entrada de video RCA',
        description: 'Cámara de reversa universal con 8 LED de alta luminosidad para visión nocturna nítida, incluso en parqueaderos oscuros. Lente gran angular que cubre todo el área trasera, líneas de guía de estacionamiento dinámicas y carcasa metálica sellada resistente al agua. Se instala en la placa o el platón trasero y se conecta por cable RCA a cualquier radio o pantalla existente — no necesitas cambiar tu equipo actual.',
        price: 89900,
        stock: 24,
        status: 'Activo',
        images: ['camara-reversa-hd.png'],
        vehicleBrand: 'Universal',
        vehicleModel: '',
    },
    {
        id: 'REF109',
        slug: 'radio-9-2din',
        name: 'Radio Android 9" 2 DIN — 4GB/64GB, CarPlay & Android Auto',
        category: 'Radios Android',
        brand: 'JNB Android',
        compatibility: 'Universal 2 DIN — apto para cualquier tipo de vehículo',
        description: 'Radio Android de 9 pulgadas en formato 2 DIN, con 4GB de RAM y 64GB de almacenamiento para navegar sin trabarse. Corre Android 15, con Apple CarPlay y Android Auto, Bluetooth y entrada USB. Incluye Magic Box (adaptador para CarPlay/Android Auto inalámbrico) y cámara de reversa de regalo, con guía de estacionamiento y visión nocturna en pantalla. Apto para cualquier tipo de vehículo.',
        price: 420000,
        stock: 18,
        status: 'Activo',
        images: ['radio-9-2din.png'],
        vehicleBrand: 'Universal',
        vehicleModel: '',
    },
    {
        id: 'REF110',
        slug: 'carplay-inalambrico-2en1',
        name: 'Adaptador Inalámbrico CarPlay & Android Auto 2 en 1',
        category: 'Multimedia y Conectividad',
        brand: 'JNB Connect',
        compatibility: 'Radios y pantallas con Apple CarPlay o Android Auto de fábrica (cableado)',
        description: 'Convierte tu Apple CarPlay o Android Auto cableado en inalámbrico en segundos. Es un adaptador "plug & play": lo conectas una sola vez al puerto USB original de tu radio y, de ahí en adelante, tu teléfono se enlaza solo por WiFi cada vez que subes al carro — sin cables. Compatible con Waze, Spotify, WhatsApp, Google Maps y la mayoría de apps de tu teléfono. Conexión estable, arranque rápido y actualizaciones por WiFi (OTA).',
        price: 199900,
        stock: 30,
        status: 'Activo',
        images: ['carplay-inalambrico-2en1.png'],
        vehicleBrand: 'Universal',
        vehicleModel: '',
    },
    {
        id: 'REF111',
        slug: 'subwoofer-jnb-caja',
        name: 'Subwoofer JNB en Caja + Kit de Cableado',
        category: 'Car Audio',
        brand: 'JNB Audio',
        compatibility: 'Universal — cualquier vehículo con espacio en el baúl',
        description: 'Subwoofer JNB en caja sellada, con parlante de bajos reforzado y tweeter de agudos integrado en el mismo panel frontal. Cuerpo forrado en enchapado texturizado, resistente a golpes y vibración. Incluye kit de cableado completo (cable de poder, tierra, RCA y fusible) listo para conectar a tu amplificador — solo falta instalarlo.',
        price: 249900,
        stock: 14,
        status: 'Activo',
        images: ['subwoofer-jnb-caja.png'],
        vehicleBrand: 'Universal',
        vehicleModel: '',
    },
    {
        id: 'REF112',
        slug: 'led-toyota-parrilla',
        name: 'Emblema LED Toyota Iluminado para Parrilla',
        category: 'Iluminación LED',
        brand: 'JNB-IHK',
        compatibility: 'Toyota — parrilla frontal (Land Cruiser, Prado, Fortuner y similares)',
        description: 'Letras "TOYOTA" iluminadas en LED para reemplazar el emblema original de la parrilla frontal. Encendido junto con las luces de posición del vehículo, con acabado cromado de fábrica de día y letras blancas iluminadas de noche. Instalación directa sobre el emblema original, sin cortes ni empalmes.',
        price: 129900,
        stock: 20,
        status: 'Activo',
        images: ['led-toyota-parrilla.png'],
        vehicleBrand: 'Toyota',
        vehicleModel: 'Land Cruiser, Prado, Fortuner',
    },
    {
        id: 'REF113',
        slug: 'amplificador-jnb-sl2000',
        name: 'Amplificador JNB SL-2000 4 Canales',
        category: 'Car Audio',
        brand: 'JNB Audio',
        compatibility: 'Universal — cualquier sistema de car audio',
        description: 'Amplificador de 4 canales JNB SL-2000, pensado para llevar tu sistema de sonido a otro nivel de potencia y claridad. Chasís en aluminio con disipador de calor integrado para uso prolongado sin recalentarse. Terminales chapados en oro para una conexión estable y sin pérdida de señal. Compatible con parlantes, tweeters y subwoofers.',
        price: 349900,
        stock: 10,
        status: 'Activo',
        images: ['amplificador-jnb-sl2000.png'],
        vehicleBrand: 'Universal',
        vehicleModel: '',
    },
];

export const seedSampleCatalogIfEmpty = (): void => {
    if (countProducts() > 0) return;
    for (const product of sampleCatalog) upsertProduct(product);
    console.warn(`⚠️  Catálogo vacío: se cargaron ${sampleCatalog.length} productos reales de arranque. Los precios y el stock son valores iniciales — actualízalos importando tu inventario real (ver "npm run import:excel").`);
};
